- name: '{{ app_name }}, nginx: set facts'
  set_fact:
    app_nginx_title: '{{ app_name }}, nginx'
    server_config_dest: '/etc/nginx/sites-available/{{ app_name }}'
    template_file: "{{ './app.nginx.with-cert.j2' if cert_files_in_target_are_present else './app.nginx.no-cert.j2' }}"
    rproxy_conf_file_bname: '{{ app_name }}-reverse-proxy'

- name: '{{ app_nginx_title }}: create app config file'
  become: yes
  vars:
    server_name: "{{ '# ... no domains' if not cert_files_in_target_are_present else ['server_name', ' ', ' '.join(domains), ';'] | join('') }}"
  ansible.builtin.template:
    src: '{{ template_file }}'
    dest: '{{ server_config_dest }}'

- name: '{{ app_nginx_title }}: create symlink to sites-enabled dir'
  become: yes
  ansible.builtin.file:
    src: '{{ server_config_dest }}'
    dest: '/etc/nginx/sites-enabled/{{ app_name }}'
    state: link

- name: '{{ app_nginx_title }}: unset facts'
  set_fact:
    app_nginx_title:
    server_config_dest:
    template_file:
