# Place the config file under ./secrets directory

deployments:
  $NAME_OF_DEPLOYMENT:
    infra:
      - TODO
    cm:
      # If none is specified, will use the usual SSH id file found in the user's $HOME/.ssh dir.
      ssh_identity_file: /path/to/ssh_identity_file

      domain: www.example.com
      ips:
        - 1.2.3.4
        - 4.3.2.1

      # Can't use "remote_user" because it's a reserved name in Ansible.
      user_with_remote_access: 'remote'
      # No remote access. Will own the app dir, will run the deployment processes.
      deploy_user: 'deploy'

      # Could be the same as $NAME_OF_DEPLOYMENT
      app_dir: /apps/app-name

      repo: https://github.com/user/repo

      # This whole dir will be copied to app_dir. This path could be relative to the config file dir (TODO).
      secrets_dir: /path/to/secrets/dir

      # For configuring TLS certificates, etc.
      email: 'user@example.com'
