# Place the config file under ./secrets directory

deployments:
  $NAME_OF_DEPLOYMENT:
    infra:
      - TODO
    cm:
      domain: www.example.com
      ips:
        - 1.2.3.4
        - 4.3.2.1
      user_with_remote_access: 'remote' # Can't use "remote_user" because it's a reserved name in Ansible
      deploy_user: 'deploy' # No remote access

      app_dir: /apps/app-name # Could be the same as $NAME_OF_DEPLOYMENT
      repo: https://github.com/user/repo
      secrets_dir: /path/to/secrets/dir # This whole dir will be copied to app_dir
