- name: 'nginx: set facts'
  set_fact:
    nginx_title: 'nginx'

- name: '{{ nginx_title }}: install packages'
  become: yes
  apt:
    pkg:
      - nginx
    install_recommends: no

- name: '{{ nginx_title }}: create ACME challenge config'
  become: yes
  ansible.builtin.file:
    dest: '{{ html_path }}{{ acme_challenge_sub_dir }}'
    state: directory

- name: '{{ nginx_title }}: create ACME challenge config'
  become: yes
  ansible.builtin.template:
    src: './acme-challenge.nginx.j2'
    dest: '/etc/nginx/sites-available/acme-challenge'

- name: '{{ nginx_title }}: create ACME challenge config'
  become: yes
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/acme-challenge'
    dest: '/etc/nginx/sites-enabled/acme-challenge'
    state: link

- name: '{{ nginx_title }}: clean up'
  become: yes
  ansible.builtin.file:
    dest: '/etc/nginx/sites-enabled/default'
    state: absent

- name: '{{ nginx_title }}: clean up'
  become: yes
  ansible.builtin.file:
    dest: '/etc/nginx/sites-available/default'
    state: absent

- name: '{{ nginx_title }}: unset facts'
  set_fact:
    nginx_title:
