- name: '{{ subgroup_title }}, nginx: set facts'
  set_fact:
    nginx_title: '{{ subgroup_title }}, nginx'
    backend_port: '{{ backend_port }}'
    server_config_dest: '/etc/nginx/sites-available/{{ app_name }}'
    template_file: "{{ './app.nginx.with-cert.j2' if cert_files_are_present else './app.nginx.no-cert.j2' }}"

- name: '{{ nginx_title }}: install packages'
  become: yes
  apt:
    pkg:
      - nginx
    install_recommends: no

- name: '{{ nginx_title }}: create server config file'
  become: yes
  vars:
    server_name: "{{ '# ... no domains' if not cert_files_are_present else ['server_name', ' ', ' '.join(domains), ';'] | join('') }}"
  ansible.builtin.template:
    src: '{{ template_file }}'
    dest: '{{ server_config_dest }}'

- name: '{{ nginx_title }}: create symlink to sites-enabled dir'
  become: yes
  ansible.builtin.file:
    src: '{{ server_config_dest }}'
    dest: '/etc/nginx/sites-enabled/{{ app_name }}'
    state: link

- name: '{{ nginx_title }}: unset facts'
  set_fact:
    nginx_title:
    backend_port:
    server_config_dest:
    template_file:
