---
- name: 'Web server and TLS: set facts'
  set_fact:
    title: 'Web server and TLS'

- import_tasks: ./no-domain.yml
  when: main_domain is not defined

- import_tasks: ./with-domains.yml
  vars:
  when: main_domain is defined

- name: '{{ title }}: unset facts'
  set_fact:
    title:
