---
- name: 'Web server and TLS: set facts'
  set_fact:
    title: 'Web server and TLS'
    _html_path: '/var/www/html'

- import_tasks: ./nginx.yml
  vars:
    html_path: '{{ _html_path }}'
    acme_challenge_sub_dir: '/.well-known/acme-challenge/'

- import_tasks: ./letsencrypt.yml
  when: main_domain is defined
  vars:
    html_path: '{{ _html_path }}'

- name: '{{ title }}: unset facts'
  set_fact:
    title:
