- name: 'With domains: set facts'
  set_fact:
    with_domains_title: 'With domains'

- import_tasks: ./nginx.yml
  vars:
    subgroup_title: '{{ with_domains_title }}'

- import_tasks: ./letsencrypt.yml

- name: '{{ with_domains_title }}: unset facts'
  set_fact:
    with_domains_title:
