---
- name: 'App: set facts'
  set_fact:
    app_tasks_title: 'App'

- import_tasks: './git.yml'

- import_tasks: './app-specific.yml'

# - name: '{{ app_tasks_title }}, app: inside container or not'
#   become: yes
#   ansible.builtin.command:
#     argv:
#       - grep
#       - -sq
#       - 'docker\|lxc'
#       - /proc/1/cgroup
#   register: is_inside_container
#   ignore_errors: yes

# - import_tasks: ./systemd.yml
#   when: is_inside_container.failed

# - import_tasks: ./sysv.yml
#   when: not is_inside_container.failed

- name: '{{ app_tasks_title }}: unset facts'
  set_fact:
    app_tasks_title:
